---
model_config:
  discriminator_config:
    batch_size: 2048
    layers:
    - units: 256
      activation: sigmoid
    - units: 1
      activation: sigmoid
    learning_rate: -0.1
    initialization_variance: 0.1
  generator_config:
    batch_size: 2048
    noise_type: uniform
    noise_dim: 1
    layers:
    - units: 128
      activation: sigmoid
    - units: 1
      activation: sigmoid
    learning_rate: -0.1
    initialization_variance: 1
  target_distribution:
    name: normal
    mean: 0
    standard_deviation: 1
dashboard_config:
  screen_height: 200
  screen_width: 300
  generator_graph:
    show_optimal_generator: true
    show_generator_histogram: 20
    show_generator_kernel: true
  discriminator_graph:
    show_optimal_discriminator_kernel: true
    show_discriminator: true



