---
model_config:
  discriminator_config:
    batch_size: 4096
    layers:
    - type: dense
      units: 1024
    - type: leaky_relu
      alpha: 0.2
    - type: dense
      units: 1
    - type: sigmoid
    optimiser:
      type: adam
      learning_rate: 0.05
  generator_config:
    batch_size: 4096
    noise_type: uniform
    noise_dim: 4
    layers:
    - type: dense
      units: 2048
    - type: leaky_relu
      alpha: 0.2
    - type: dense
      units: 1
    optimiser:
      type: adam
      learning_rate: 0.002
  target_distribution:
    name: bimodal
    mean_one: -1.5
    mean_two: 1.5
    standard_deviation: 0.6
  training_method: unrolled
  training_params:
    k: 5
dashboard_config:
  screen_height: 200
  screen_width: 300
  generator_graph:
    show_optimal_generator: true
    show_generator_histogram: 20
    show_generator_kernel: true
  discriminator_graph:
    show_optimal_discriminator_kernel: true
    show_discriminator: true



