---
model_config:
  discriminator_config:
    batch_size: 4096
    layers:
    - type: dense
      units: 1024
    - type: leaky_relu
      alpha: 0.2
    - type: dense
      units: 1
    optimiser:
      type: adam
      learning_rate: 0.02
  generator_config:
    batch_size: 4096
    noise_type: uniform
    noise_dim: 4
    layers:
    - type: dense
      units: 1024
    - type: leaky_relu
      alpha: 0.2
    - type: dense
      units: 1
    optimiser:
      type: adam
      learning_rate: 0.001
  target_distribution:
    name: normal
    mean: 0
    standard_deviation: 1
  gan_type: wasserstein
  gan_params:
    clipping:
      0.02
  training_method: standard
  training_params: {}
dashboard_config:
  screen_size: [500, 200]
  plot_range: [-6, 6]
  offset: 0.5
  histogram_config:
    buckets: 100
    show_histogram: true
  graph_config:
    show_graphs: true
    points: 50
    show_optimal_generator: true
    show_generator_kernel: true
    show_optimal_discriminator_kernel: true
    show_discriminator: true



