---
model_config:
  batch_size: 2048
  discriminator_config:
    layers:
    - units: 128
      activation: sigmoid
    - units: 1
      activation: sigmoid
    learning_rate: 0.0001
    initialization_variance: 0.01
  generator_config:
    noise_type: uniform
    noise_dim: 1
    layers:
    - units: 128
      activation: sigmoid
    - units: 128
      activation: sigmoid
    - units: 1
      activation: sigmoid
    learning_rate: 0.0001
    initialization_variance: 0.01
  target_distribution:
    name: normal
    mean: 0
    standard_deviation: 1
dashboard_config:
  screen_height: 200
  screen_width: 300
  generator_graph:
    show_optimal_generator: true
    show_generator_histogram: 20
    show_generator_kernel: true
  discriminator_graph:
    show_optimal_discriminator_kernel: true
    show_discriminator: true



